### ISSUE TITLE
[Crescendo 2.0] feature/rooms pre-merge task list

### ISSUE THREAD

**Issue by adelyte-chris** [adelyte/crescendo#12]
All tasks should be finished before `feature/rooms` merges with `develop`.

#### Move Rooms Specs
- [x] Only rooms 1, 3, 4, 5, 6, and 8 should be available.
- [x] If a room has no source, its description should be "Off" and its icon should be blank.
- [x] If a room has a source, its description should be the source name and its icon should be the source icon.

#### Watch and Listen Specs
- [x] Room 1 has defined sources 1-5, 41-45, and 51.
- [x] Rooms 3-5 and 8 have defined sources in `Room:Sources`.
- [x] Other rooms have default sources from `Sources:Default Sources`.
- [x] Sources 41-45 appear in the listen menu.
- [x] Other sources appear in the watch menu.
- [x] The source description should say the room or rooms with the source present.

#### Share Source Specs
- [x] Only rooms that have the source available can be shared.
- [x] Only rooms in the move list can be shared.
- [x] Volume up, down, and mute work as expected.
- [x] Power off works as expected.

#### Rooms
- [x] Slots and parameters should be consistent and correct.
- [x] Internal symbols and signals should be organized, consistent, and documented.

#### Sources
- [x] Slots and parameters should be consistent and correct.
- [x] Internal symbols and signals should be organized, consistent, and documented.

#### Rooms-Sources Controller
- [x] Slots and parameters should be consistent and correct.
- [x] Internal symbols and signals should be organized, consistent, and documented.
- [x] SIMPL+ logic should be organized, consistent, documented, and correct.

**Comment by adelyte-austin** [comment]
Changing to Room 3 works, but highlights Room 4 in the subpage reference list.

**Comment by adelyte-austin** [comment]
For rooms that are off, we can display the power icon, which may look better than leaving the gap on the left.
<img width="339" alt="screen shot 2015-10-22 at 1 30 39 pm" src="https://cloud.githubusercontent.com/assets/2684605/10677460/57292778-78c1-11e5-98d9-5853ee77f7fa.png">

**Comment by adelyte-austin** [comment]
Sharing Room 3's source hides all but Rooms 1 and 3 in sharing menu. The digital visibility joins for rooms that should be showing are set to 0.

**Comment by adelyte-austin** [comment]
Room's source feedback does not show in list. The T-XX_Watch/Listen_XX_Source_Matches signal is not asserting.

**Comment by adelyte-chris** [comment]
Fixed room selected feedback in move rooms list.

**Comment by adelyte-austin** [comment]
Single clicking share volume up or down sends panel side volume signal to processor, but does not move volume target at Switcher.

**Comment by adelyte-austin** [comment]
Selecting a Watch or Listen source does not generate a Route~ from Rooms-Sources Controller module.

**Comment by adelyte-chris** [comment]
This checklist was finished sometime before [feature/demo](https://github.com/adelyte/crescendo/tree/feature/demo).
