### ISSUE TITLE
[Crescendo 2.1] Scope of Work Checklist

### ISSUE THREAD

**Issue by adelyte-chris** [adelyte/crescendo#21]
# "The Loft"
#### Global

Interfaces consist of
- [x] Two (2) Apple iPads and
- [x] Two (2) Apple iPhones,

which provide roaming and external access to all rooms and subsystems.

Video Distribution consists of
- [x] One (1) Crestron DM-MD6x4

with source inputs for
- [x] One (1) TiVo Pro
- [x] One (1) Sony Blu-ray
- [x] One (1) AppleTV
- [x] One (1) Nintendo Wii U

Audio Distribution consists of
- [x] One (1) Crestron SWAMP-24x8

with source inputs for
- [x] One (1) Crestron NSP-1
- [x] One (1) Sonos Connect (note: users should be able to launch the Sonos app from inside of Crestron App)
- [x] One (1) TiVo Pro
- [x] One (1) Sony Blu-ray, "CD"
- [x] One (1) AppleTV, "AirPlay"

Climate control is provided by
- [x] One (1) Crestron CHV-TSTAT for the main area,
- [x] One (1) Crestron CHV-TSTAT for the master suite, and
- [x] One (1) Crestron CHV-TSTAT for the guest suite.
#### Media Room

Equipment consists of
- [x] One (1) Crestron TSR-302 remote control;
- [x] One (1) Crestron DM-MD6x4 video switcher output;
- [x] One (1) TBD _Crestron Connected_ A/V receiver;
- [x] One (1) TBD 5.1 surround sound speakers;
- [x] One (1) OFE IR-controlled television.
#### Kitchen

Equipment consists of
- [x] One (1) Crestron HR-150 remote control;
- [x] One (1) Crestron DM-MD6x4 video switcher output;
- [x] One (1) OFE IR-controlled television;
- [x] One (1) Crestron SWAMP audio switcher output;
- [x] Four (4) TBD in-ceiling speakers.
##### Notes
- [x] Video sources will play through the television speakers, and
- [x] Audio sources will play through ceiling speakers.
#### Dining Room

Equipment consists of
- [x] One (1) Crestron SWAMP audio switcher output;
- [x] Two (2) TBD in-ceiling speakers.
#### Office

Equipment consists of
- [x] One (1) Crestron SWAMP audio switcher output;
- [x] Two (2) TBD in-ceiling speakers.
#### Master Bedroom
- [x] One (1) Crestron HR-150 remote control;
- [x] One (1) TBD IR-controlled television with an optical audio output;
- [x] One (1) Sonos PLAYBAR sound bar;
- [x] One (1) Crestron SWAMP audio switcher output;
- [x] One (1) TiVo Mini;
- [x] One (1) Apple TV;
- [x] Four (4) TBD in-ceiling speakers.
##### Notes
- [x] Video sources will play through the sound bar, and
- [x] Audio sources will play through ceiling speakers;
- [x] "Smart TV" apps will be available available as a source.
#### Master Bathroom

Equipment consists of
- [x] One (1) Crestron SWAMP audio switcher output;
- [x] Two (2) TBD in-ceiling speakers.
### Expansion

Subject to customer satisfaction, the system will expand to include outdoor audio, guest suite audio and video, office video, and full utilization of video distribution. All areas are prewired for audio, video, and local control.

**Comment by adelyte-austin** [comment]
"The Loft" adheres to all scope requirements.

**Comment by adelyte-wes** [comment]
## Media Room Projector & Crescendo Cloud Upgrade

#### Media Room
Upgrading existing display to
- [x] One (1) Sony RS-232 controlled projector;
- [x] Add Lamp Hours to Crescendo Cloud Service.

#### Crescendo Cloud
- [x] Update to the latest version of the Crescendo Cloud driver;
- [x] Confirm Media Room Lamp Hours in addition to Crescendo 2.0 out-of-the-box Room data.

**Comment by adelyte-austin** [comment]
## IP Camera Upgrade

#### iPads
Add streaming camera images.
- [x] Four camera locations: entrance, east and west balconies, playroom;
- [x] UI should easily scale to add additional cameras in the future.
